[package]
name = "compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
ast = { path = "../ast" }
diagnostics = { path = "../diagnostics" }
text = { path = "../text" }
typings = { path = "../typings" }
lexer = { path = "../lexer" }
parser = { path = "../parser" }