[package]
name = "ast"
version = "0.1.0"
edition = "2021"

[dependencies]
diagnostics = { path = "../diagnostics" }
lexer = { path = "../lexer" }
text = { path = "../text" }
support = { path = "../support" }
termion = "4.0.3"
