[package]
name = "ast"
version = "0.1.0"
edition = "2021"

[dependencies]
diagnostics = { path = "../diagnostics" }
index = { path = "../index" }
lexer = { path = "../lexer" }
support = { path = "../support" }
text = { path = "../text" }
typings = { path = "../typings" }
termion = "4.0.3"
