[package]
name = "lexer"
version = "0.1.0"
edition = "2021"

[dependencies]
miette = { version = "7.2.0", features = ["fancy"] }
errors = { path = "../../utils/errors" }
text = { path = "../../utils/text" }
token = { path = "../token" }
