[package]
name = "resolver"
version = "0.1.0"
edition = "2021"

[dependencies]
diagnostics = { path = "../diagnostics" }
token = { path = "../token" }
text = { path = "../../utils/text" }
typings = { path = "../typings" }
